#! /bin/sh

sxhkd &
#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')
THIRD_MONITOR=$(xrandr | grep connected | awk '{i++}i==3'| awk '{print $1}')

sxhkd &
bspc wm -O $PRINCIPAL $SECOND_MONITOR
 #Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  bspc monitor $(bspc query -M | sed -n 3p) -d XI XII XIII XIV XV 
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
  xrandr --output $THIRD_MONITOR --$THIRD_MONITOR_SIDE-of $PRINCIPAL  
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d 1 2 3
  bspc monitor $(bspc query -M | sed -n 2p) -d 4 5 6 7 8
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
else
  bspc monitor -d 1 2 3 4 
fi

bspc config border_width         2
bspc config borderless_monocle   true

bspc config window_gap            6
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#ffebb5"
bspc config normal_border_color "#353b45"

# autostart up applications
ibus-daemon -drxR &
~/.config/polybar/launch.sh &
picom &
nitrogen --restore &
xrdb merge ~/.Xresources &

# Cursor
xsetroot -cursor_name left_ptr

# swap ctrl and caps lock
setxkbmap -option ctrl:swapcaps
