#! /bin/sh

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config borderless_monocle   true

bspc config window_gap            6
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#ff936b"
bspc config normal_border_color "#353b45"

# autostart up applications
ibus-daemon -drxR &
~/.config/polybar/launch.sh &
picom &
nitrogen --restore &
xrdb merge ~/.Xresources &
sxhkd &

# Cursor
xsetroot -cursor_name left_ptr

# swap ctrl and caps lock
setxkbmap -option ctrl:swapcaps
